### ISSUE TITLE
Flagged as malicious

### ISSUE THREAD

**Issue by Skerbergs** [KuromeSan/MCEELoginSkip#10]
Various anti-virus software mark this as a PUP or adware. I'm sure it isn't but I'm concerned about it.

Here you have a virustotal scan: https://www.virustotal.com/gui/file/bd0a5859f7b0a47671a9b5f88cd7538fc566de5c1fb109e56050def1b7714174

Edit: Gave the source code a closer look and it definitely isn't any type of malware.

**Comment by KuromeSan** [comment]
What your suppose to do is send it to Microsoft to verify its not malware, unfortunately they will probably mark it as a hacktool if I did that lol

**Comment by Skerbergs** [comment]
> 
> 
> What your suppose to do is send it to Microsoft to verify its not malware, unfortunately they will probably mark it as a hacktool if I did that lol

Makes sense, anyway, thank you.
